### ISSUE TITLE
All paths (--python-root, --submodule) should be normalized to be relative to repository root before they are processed

### ISSUE THREAD

**Issue by zomglings** [bugout-dev/infestor#6]
Currently, `infestor` raises errors when someone tries to invoke it with an unnormalized path.

Requiring users to hand-normalize paths is terrible.

**Comment by kompotkot** [comment]
```
Traceback (most recent call last):
  File "/home/ubuntu/Documents/bugout/infestor/python/.infestor/bin/infestor", line 11, in <module>
    load_entry_point('bugout-infestor', 'console_scripts', 'infestor')()
  File "/home/ubuntu/Documents/bugout/infestor/python/infestor/cli.py", line 417, in main
    args.func(args)
  File "/home/ubuntu/Documents/bugout/infestor/python/infestor/cli.py", line 87, in handle_list
    results = manage.list_calls(call_type, args.repository, args.python_root)
  File "/home/ubuntu/Documents/bugout/infestor/python/infestor/manage.py", line 309, in list_calls
    files_with_reporter = list_reporter_imports(
  File "/home/ubuntu/Documents/bugout/infestor/python/infestor/manage.py", line 248, in list_reporter_imports
    raise GenerateReporterError(
infestor.manage.GenerateReporterError: Could not find Python root (/home/ubuntu/Documents/) in configuration file (/home/ubuntu/Documents/infestor.json)
```

**Comment by zomglings** [comment]
TODO(@zomglings): Check this behavior again after @Yhtiyar 's updates in v0.0.5. May not be an issue anymore.
